		// { "grantTotal", 0 },
		// { "showShortOtterVideo", 1 },
		// { "showShortSeaIceVideo", 1 },
		// { "Improved", 0 }, 
		// { "Beat 'Em All", 0 },

		// { "LITHBasic", 0 },
		// { "LITHEasy", 0 },
		// { "LITHNormal", 0 },
		// { "LITHHard", 0 }, 
		// { "LITHInsane", 0 },
		// { "GTPBasic", 0 },
		// { "GTPEasy", 0 },
		// { "GTPNormal", 0 },
		// { "GTPHard", 0 }, 
		// { "GTPInsane", 0 },
		// { "MTIBasic", 0 },
		// { "MTIEasy", 0 },
		// { "MTINormal", 0 },
		// { "MTIHard", 0 }, 
		// { "MTIInsane", 0 },

		{ "Bird Friend", 0 },
		{ "Bird Strike", 0 },
		// { "100,000", 0 },
		// { "500,000", 0 }, 
		// { "1,000,000", 0 },
		// { "Albino Otter", 0 },
		// { "Be Insane", 0 },
		// { "Got 'Em All", 0 },
		// { "Improved New", 1 }, 
		// { "Beat 'Em All New", 1 },
		// { "Bird Friend New", 1 },
		// { "Bird Strike New", 1 },
		// { "100,000 New", 1 }, 
		// { "500,000 New", 1 },
		// { "1,000,000 New", 1 },
		// { "Albino Otter New", 1 },
		// { "Be Insane New", 1 }, 
		// { "Got 'Em All New", 1 },
		{"music pref", 1},
		{"sfx pref", 1}